### ISSUE TITLE
Add long-running e2e benchmark

### ISSUE THREAD

**Issue by Warchant** [VeriBlock/alt-integration-cpp#943]
Requirements:
- [x] Deterministically (based on size_t seed) generate series of "commands" (atomic actions) in e2e setup.  
- [x] Input is a vector of bytes.
    - interface for strategies: fuzz strategy, seed strategy
- [x] Define a list of actions (enum):
    - Mine BTC, VBK, ALT block. When block is mined, take entire (corresponding) mempool content and include in next block.
    - Create BTC TX, VBK TX, VBK POP TX. Creates a tx and stores in corresponding mempool.
    - Submit ATV, VTB, VBK, ALL. Submit corresponding payload (first, random, all in candidates).
 - [x] At the end return a struct of "statistics" (metrics).

**Comment by Mr-Leshiy** [comment]
>Input is a vector of bytes.
Already implemented;
